cmdargs:
  # Checking more strictly
  severity: style_problem

  # Enable coloring
  color: true

  # Enable Neovim syntax
  env:
    neovim: true

  stat: true

policies:
  ProhibitSetNoCompatible:
    enabled: false
  ProhibitUnnecessaryDoubleQuote:
    enabled: false
