# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: install dependencies
        run: sudo apt update && sudo apt install vim neovim vim curl
      
      - name: install node
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash
          source "$HOME/.nvm/nvm.sh"
          nvm install lts/erbium
          npm install -g neovim
      
      - name: test vim setup script
        continue-on-error: true
        run: |
            ./scripts/setup.sh -t vim
            
      - name: test neovim setup script
        run: |
            ./scripts/setup.sh
          
          
